name: Add to Project

on: pull_request

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/EllieBotDevs/projects/3
          # A GitHub personal access token with write access to the project
          github-token: "${{ secrets.GITHUB_TOKEN }}"
